branch-defaults:
  default:
    environment: worker-staging
environment-defaults:
  webserver-staging:
    branch: null
    repository: null
global:
  application_name: selstagram
  default_ec2_keyname: Artify Webserver
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Python 3.4 running
    on 64bit Amazon Linux/2.3.3
  default_region: ap-northeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
