# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20170426_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularstatistics',
            old_name='top102_ids',
            new_name='top150_ids',
        ),
        migrations.AlterField(
            model_name='popularstatistics',
            name='top150_ids',
            field=models.CharField(max_length=4096),
        ),
    ]
