# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20170501_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammedia',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
